apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app1
  template:
    metadata:
      labels:
        name: app1
    spec:
      containers:
      - name: app1
        image: techworldwithsiva/app1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    name: app1
spec:
  selector:
  # you should provide pod labels here
    name: app1
  ports:
  - name: http-port
    protocol: TCP
    # service port
    port: 80
    # pod port
    targetPort: 80
---
# Here Ingress is the resource that is capable of creating AWS ALB resource, you must provide annotations
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=DEV
    alb.ingress.kubernetes.io/group.name: cloudcamp
spec:
  ingressClassName: alb
  rules:
  - host: "app1.cloudcamp.online"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: app1
            port:
              number: 80